### PR TITLE
Advance scoring analysis

### LINKED ISSUE #33: Add support per class in the confusion table
In the current state of the table, it's really hard to make sense from it as the support is quite unknown. For example, if I have NOMpro 120 times mislabeled 90 times as NOMcom, it's not the same situation as it being mislabeled 30 times.

### PR DESCRIPTION
**Pull request by PonteIneptique**
On top of correctly blocking torch==1.2.0, I added a classification report for each class that reports for each class. This allows for qualitative analysis of the bias of "_"-classes results, *ie.* where a morphological feature is mostly absent, like "mode", as it is present only in verbs. This closes #33 

If I may, and if you are okay with this PR, could you also push a new release to pypi ?
Best,
Thibault

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hey @emanjavacas ,
I just updated the dependencies again, as the current state of sklearn does not allow for python3.7 usage.
Cheers !

**Comment by emanjavacas** [comment]
Hey @PonteIneptique ! Thanks for the PR. I will merge, push and publish!

**Comment by PonteIneptique** [comment]
Actually, a last commit is incoming
I forgot to push it :)

**Comment by emanjavacas** [comment]
Alright! I will wait

**Comment by PonteIneptique** [comment]
Done ;)

**Comment by PonteIneptique** [comment]
Thans @emanjavacas , feels go to install pie on 3.7 without hacking stuff :)

**Pull request merged**
